services:
  - type: web
    name: backslash-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: API_PREFIX
        value: api
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASS
        sync: false
      - key: REDIS_HOST
        fromService:
          name: backslash-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: backslash-redis
          type: redis
          property: port

  - type: redis
    name: backslash-redis
    ipAllowList: []
    plan: free
